apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: atom8426/ct-gateway:latest
          ports:
            - containerPort: 19091
          env:
            - name: SPRING_PROFILE
              value: "prod"
            - name: JWT_SECRET
              value: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"
            - name: USER_SERVICE_URL
              value: "http://user-service.default.svc.cluster.local:80"
            - name: BLOG_SERVICE_URL
              value: "http://blog-service.default.svc.cluster.local:80"
            - name: CODE_LLM_SERVICE_URL
              value: "http://code-llm-service.default.svc.cluster.local:80"
            - name: CODE_COMPILE_SERVICE_URL
              value: "http://code-compile-service.default.svc.cluster.local:80"
            - name: CODE_BANK_SERVICE_URL
              value: "code-bank-service.default.svc.cluster.local"