spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE-LOCAL
          predicates:
            - Path=/users/**, /auth/**, /health
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blogs/**

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

server:
  port: 19091

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka

logging:
  level:
    org.springframework.security: TRACE
