spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE-DEV
          predicates:
            - Path=/auth/**, /health, /oauth2/**, /login/**, / #인증 제외 목록
        - id: user-service
          uri: lb://USERSERVICE-DEV
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: blog-service
          uri: lb://BLOGSERVICE-DEV
          predicates:
            - Path=/blogs/**
          filters:
            - AuthFilter

  jwt:
    secret: ${JWT_SECRET}

server:
  port: 19091

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

logging:
  level:
    org.springframework.security: TRACE


